FROM node:20-bullseye as builder
WORKDIR /app
COPY . .
WORKDIR /app/frontend
RUN npm install
RUN npm install -g @angular/cli
RUN ng build

FROM nginx:latest
COPY k8s/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/dist/frontend/browser /usr/share/nginx/html