kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: sommerlager-frontend
  labels:
    app: sommerlager-frontend
  annotations:
    app: sommerlager-frontend
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - sommerlager.goetz01.de
      secretName: sommerlager-frontend-ingress-tls
  rules:
    - host: sommerlager.goetz01.de
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 80